### ISSUE TITLE
Create a prototype of "Tel map" front end

### ISSUE THREAD

**Issue by YsuOS** [YsuOS/open-motherbase#4]
# task detail
- create "Tel Map" which is like Yes/No question flow chart.
- we can go to Tel map by clicking "Tel map" under Operation/Tools section in motherbase top page
- Then, you can see the first page like below.
  - there is one question; `1. Are you a man or woman?`
  - there are two button; `man`, `woman`
    - you can go to the second page by clicking `man` button; you can see the example below
    - you can go to the third page by clicking `woman` button; you can see the example below
```
===first page===
1. Are you a man or woman?
man   
woman
```
- after click `man` button, you can come to the second page
  - there is also one question `2. Do you workout?`
  - And also there are two button again; `yes` and `no`button.

```
===second page===
2. Do you workout?
yes 
no
```

# task level
1/5 (beginner)

# programming language
- html

# what to do?
- you should write html

1. ~~you create `first` file in `internal/article/tools{or operations}/Tel/`~~
  - ~~if you can't find some directory, you can create directories by yourself~~
1. In this task, you create `first` and `second` files in `internal/article/tools{or operations}/` directly.
  - So in index(top) page, you can see first and second link in Tools section
  - In this task, it is expected behavior!
2. write down each question and put buttons in html
  - hint: to create buttons, you should use `<a href>`tag or `<button>`tag

**Comment by kosuke0320** [comment]
===first page===
1. Do you work?
yes<<<---click the button, then move on the second page
no<<<---click the button, then move on the third page

===second page===
2. Are you satisfied with your workplace?
yes<<<---click the button, then move on the fourth page
no<<<---click the button, then move on the fifth page

===third page===
3.Are you student?
yes<<<---click the button, then move on the sixth page
no<<<---click the button, then move on the seventh page

===fourth page===
4. Do you stay your workplace forever?
yes<<<---click the button, then move on the eighth page
no<<<---click the button, then move on the ninth page

===fifth page===
5. Do you consider that changed your workplace?
yes<<<---click the button, then move on the tenth page
no<<<---click the button, then move on the eleventh page

**Comment by kosuke0320** [comment]
I'm done. 
Could you please check it?

**Comment by YsuOS** [comment]
I request 2 things about it for you.

# development process
Could you read below again?
you should follow these steps in all of the development.
https://github.com/YsuOS/open-motherbase#github

you did only **3 and 4** !!
```
1. go to "Projects" tab in Github and pick up a new task you want to develop
2. move the task you picked up to "In progress" column from "To do" column
3. please do the task!
4. after finish your task, send pull requests
5. link the pull request to related issue task
6. brush up and administrator will merge the request
7. well done! go to 1. again!
```

# task detail
I'm sorry for poor explanation about this task.
I'll explain it in more detail.
Give me a moment pls.

**Comment by YsuOS** [comment]
I updated task detail. please check above comments

**Comment by kosuke0320** [comment]
![image](https://user-images.githubusercontent.com/63537539/80856116-15f16480-8c82-11ea-924e-c111de72b191.png)

![image](https://user-images.githubusercontent.com/63537539/80856119-1db10900-8c82-11ea-8f55-d4403899df1c.png)

![image](https://user-images.githubusercontent.com/63537539/80856124-26a1da80-8c82-11ea-8edb-9091628f1024.png)
